## pytorch from scratch


In [1]:
import torch

In [2]:
# version
print(torch.__version__)

2.3.0+cpu


 ### Introduction to tensor

In [3]:
## What is a Tensor ?? How differ from numPy array ??
## Tensor is a fundamental data structure, representing multidimensional array..
## Similar to numPy, but addictionaly have featurs like GPU acceleration (works in gpu).
## Tensor are the basic building blocks of a neural network
# creating tensor
# scalar (single number) # dim = 0
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Print the diamension of the scalar tensor
scalar.ndim

0

In [5]:
# get python integer from tensor
scalar.item()

7

In [6]:
a = scalar.item()
type(a)

int

In [7]:
# vector (Number with direction) # dim = 1
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX (2 dimensional array of numbers) # dim = 2
MATRIX = torch.tensor([[2, 3],
                      [3, 4]])
MATRIX

tensor([[2, 3],
        [3, 4]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([2, 3])

In [14]:
# TENSOR (n dimensional array of number) # dim = could be any dimension
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9,]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
# https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
TENSOR[0,0]

tensor([1, 2, 3])

In [20]:
# Random tensor creation
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9060, 0.5568, 0.4011, 0.1513],
        [0.4950, 0.6364, 0.3322, 0.3164],
        [0.5822, 0.3558, 0.6802, 0.5722]])

In [21]:
random_tensor.shape

torch.Size([3, 4])

In [22]:
random_tensor.ndim

2

In [23]:
# create a random tensor tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) # height, width color channels(rgb)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
# random_image_tensor  --> print the tensor

In [25]:
# creating ones and zeros tensor
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
zeros_tensor = torch.zeros(size = (2,3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
ones_tensor * random_tensor

tensor([[0.9060, 0.5568, 0.4011, 0.1513],
        [0.4950, 0.6364, 0.3322, 0.3164],
        [0.5822, 0.3558, 0.6802, 0.5722]])

In [28]:
zeros_tensor.dtype

torch.float32

In [29]:
ones_tensor.dtype

torch.float32

In [30]:
## creating a tensor in a range and tensor-like
range_tensor = torch.range(0,10)
range_tensor

/tmp/ipykernel_7163/114453004.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
arange_tensor = torch.arange(4,15)
arange_tensor

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arange_tensor = torch.arange(8)
arange_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
arange_tensor = torch.arange(5,60,5) ## start, end, step
arange_tensor

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [34]:
## tensor like
arange_tensor_like = torch.ones_like(arange_tensor)
arange_tensor_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
arange_tensor_like = torch.zeros_like(arange_tensor) ## input= arange_tensor
arange_tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
arange_tensor_like = torch.rand_like(ones_tensor)
arange_tensor_like

tensor([[0.2301, 0.7045, 0.2868, 0.5403],
        [0.9539, 0.2531, 0.8434, 0.4713],
        [0.1106, 0.9257, 0.2100, 0.9953]])

In [37]:
## Tensor datatypes
float_32_tensor = torch.rand(2,3,dtype= None)
float_32_tensor

tensor([[0.3511, 0.2975, 0.2146],
        [0.4927, 0.3255, 0.9506]])

In [38]:
float_32_tensor.dtype

torch.float32

In [39]:
d_tensor = torch.rand(2,3, dtype= torch.float16, ## float16, float32, float64
                      device = None, ## device may be cpu, gpu , cuda , tpu...
                      requires_grad= False) ## for tracking gradient
d_tensor

tensor([[0.4009, 0.0278, 0.3027],
        [0.1094, 0.7388, 0.1763]], dtype=torch.float16)

In [40]:
## Type conversion
d_tensor = d_tensor.type(torch.float32)
d_tensor.dtype

torch.float32

In [41]:
## Getting information from tensor
sample_tensor = torch.rand(3,4)
print(sample_tensor)
print('datatype :', sample_tensor.dtype)
print('size :', sample_tensor.size()) ## sample_tensor.shape
print('device :', sample_tensor.device)

tensor([[0.8631, 0.2556, 0.1433, 0.6601],
        [0.7312, 0.9558, 0.5016, 0.4417],
        [0.0029, 0.4543, 0.3902, 0.3075]])
datatype : torch.float32
size : torch.Size([3, 4])
device : cpu


In [42]:
## Tensor operations 
## (addition, substraction, multiplication, division, matrix multiplication)
op_tensor = torch.tensor([1,2,3])
print(op_tensor + 10)
op_tensor

tensor([11, 12, 13])


tensor([1, 2, 3])

In [43]:
print(op_tensor * 100)
op_tensor

tensor([100, 200, 300])


tensor([1, 2, 3])

In [44]:
print(op_tensor - 1)
op_tensor

tensor([0, 1, 2])


tensor([1, 2, 3])

In [45]:
## pytorch inbuilt function

print(torch.sub(op_tensor, 10)) ## torch.add, torch.mul, torch.div, torch.sub
op_tensor

tensor([-9, -8, -7])


tensor([1, 2, 3])

In [46]:
## matrix multiplication
## 1. element wise (scalar multiplication)
## 2. matrix wise  (Dot product, "row with column") 
## https://www.mathsisfun.com/algebra/matrix-multiplying.html
print(op_tensor * op_tensor) ## element wise

tensor([1, 4, 9])


In [47]:
## matrix wise
print(op_tensor)
torch.matmul(op_tensor, op_tensor) ## 1*1 + 2*2 + 3*3

tensor([1, 2, 3])


tensor(14)

In [48]:
1*1 + 2*2 + 3*3

14

In [49]:
%%time 
value = 0 
for i in range(len(op_tensor)):
    value += op_tensor[i] * op_tensor[i]
print(value)

tensor(14)
CPU times: user 441 µs, sys: 369 µs, total: 810 µs
Wall time: 672 µs


In [50]:
%%time
torch.matmul(op_tensor, op_tensor) ## @ == matmul (op_tensor @ op_tensor)

CPU times: user 123 µs, sys: 103 µs, total: 226 µs
Wall time: 174 µs


tensor(14)

In [51]:
%%time 
1*1 + 2*2 + 3*3

CPU times: user 1e+03 ns, sys: 1e+03 ns, total: 2 µs
Wall time: 3.58 µs


14

In [52]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 7))
## for matrix multiplication the inner dimensions need to be same and the resulting matrix shape is (3,7), which is the outer dimension
## http://matrixmultiplication.xyz/

tensor([[0.2033, 0.1139, 0.0826, 0.1400, 0.0999, 0.0809, 0.0823],
        [1.1135, 0.8404, 0.3846, 0.8452, 0.7537, 0.6408, 0.4811],
        [0.0508, 0.0566, 0.0118, 0.0451, 0.0518, 0.0459, 0.0245]])

In [53]:
## Transpose of a tensor
sample_tensor = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
sample_tensor, sample_tensor.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [54]:
sample_tensor.T, sample_tensor.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [55]:
## Find min, max, mean, sum ..(tensor aggrgation)
sample_tensor.min(), torch.min(sample_tensor) ## can be find using two method

(tensor(1), tensor(1))

In [56]:
sample_tensor.max(), torch.max(sample_tensor)

(tensor(6), tensor(6))

In [57]:
sample_tensor.mean() ## Mean can be found only for float or complex dtype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
## So to find mean convert it into float
sample_tensor.type(torch.float32).mean(), torch.mean(sample_tensor.type(torch.float32))

(tensor(3.5000), tensor(3.5000))

In [59]:
sample_tensor.sum(), torch.sum(sample_tensor)

(tensor(21), tensor(21))

In [60]:
## Find the positional min, max index
print(sample_tensor)
sample_tensor.argmax(), sample_tensor.argmin()
## At index 5 : largest value and at index 0 : min value

tensor([[1, 2],
        [3, 4],
        [5, 6]])


(tensor(5), tensor(0))

In [61]:
# Reshape, View, Stacking..
# Reshaping ==> return tensor with desired shape
sample_tensor = torch.arange(1., 7.)
sample_tensor, sample_tensor.shape

(tensor([1., 2., 3., 4., 5., 6.]), torch.Size([6]))

In [62]:
sample_tensor.reshape(1, 6).shape, sample_tensor.shape

(torch.Size([1, 6]), torch.Size([6]))

In [63]:
a = sample_tensor.reshape(1,6)
a, sample_tensor

(tensor([[1., 2., 3., 4., 5., 6.]]), tensor([1., 2., 3., 4., 5., 6.]))

In [64]:
a[0] = 2 ## When we change the value of a it also affect the orginal tensor too..

In [65]:
a, sample_tensor

(tensor([[2., 2., 2., 2., 2., 2.]]), tensor([2., 2., 2., 2., 2., 2.]))

In [66]:
## But reshape sometimes return a view and sometimes return a copy
## In the above case it return a view
## Sometimes it return the copy

In [67]:
## View ==> return tensor with desired shape,
## view share the same memory of the orginal tensor
b = sample_tensor.view(2,3)
b, b.shape

(tensor([[2., 2., 2.],
         [2., 2., 2.]]),
 torch.Size([2, 3]))

In [68]:
b[0] = 1

In [69]:
b, sample_tensor ## when change the b it also affect the orginal tensor

(tensor([[1., 1., 1.],
         [2., 2., 2.]]),
 tensor([1., 1., 1., 2., 2., 2.]))

In [70]:
## Stack ==> combines tensor each other
## dim = 0 ==> add tensor vertically ::: dim = 1 ==> add tensor horizontally
c = torch.stack([sample_tensor, sample_tensor, sample_tensor], dim = 0)
c, c.shape

(tensor([[1., 1., 1., 2., 2., 2.],
         [1., 1., 1., 2., 2., 2.],
         [1., 1., 1., 2., 2., 2.]]),
 torch.Size([3, 6]))

In [71]:
## Squeeze and Unsqueeze
## Squeeze ==> remove all single dimension from tensor
## Unsqueeze ==> add a dimension
d = sample_tensor.unsqueeze(0)

In [72]:
d.shape, sample_tensor.shape ## There added a dimesion

(torch.Size([1, 6]), torch.Size([6]))

In [73]:
d.squeeze().shape, sample_tensor.shape ## Added dimesion is removed!!..

(torch.Size([6]), torch.Size([6]))

In [74]:
## Permute ==> rearrange tensor in specified order
### https://pytorch.org/docs/stable/generated/torch.permute.html
sample_tensor = torch.rand(1,2,3)
sample_tensor.shape ## Here the dimension is 1,2,3
## considering the index of the dimensions we can say that in 0 index -> 1,
## 1 index -> 2, 2 index -> 3 so we can permute the dimesion with this index values, as given below
sample_tensor.permute(1,0,2).shape
## Change the 0 index to second, 1 index to first, 2 index to 3...

torch.Size([2, 1, 3])

In [75]:
## Selecting data from tensor(Indexing)
## Similar to numPy array
new_tensor = torch.arange(1,10).reshape(1,3,3)
new_tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [76]:
new_tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
new_tensor[0,2] ## Access rows ==> [0,0], [0,1], [0,2]

tensor([7, 8, 9])

In [78]:
## Also slice this like this :
new_tensor[0][2]

tensor([7, 8, 9])

In [79]:
new_tensor[0,0,2] ## Slice elements like this

tensor(3)

In [80]:
 ## Another way :
new_tensor[:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
new_tensor[:,1] ## Slice rows

tensor([[4, 5, 6]])

In [82]:
new_tensor[:,:,2] ## Slice columns 

tensor([[3, 6, 9]])

In [83]:
new_tensor[:,1:,0]

tensor([[4, 7]])

In [84]:
new_tensor[:,2:,1] ## Slice with row and cloumn

tensor([[8]])

### NumPy

In [85]:
## Popular scientific python numerical computing library
import numpy as np

In [86]:
array = np.arange(1.,10.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [87]:
array.dtype ## Arrays default float dtype is float64, int default is int64, thus when convert to tensor it also have float64

dtype('float64')

In [88]:
## Tensor's float default dtype is float32
torch.arange(1.,10.).dtype

torch.float32

In [89]:
## So if to want to change the dtype while converting
a = torch.from_numpy(array).type(torch.float32)
a.dtype

torch.float32

In [90]:
## When modify the NumPy array in place, the changes are reflected in the tensor, both the array and the tensor share the same memory.
array[0] = 3
array, tensor

(array([3., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [91]:
## When reassign the NumPy array to a new array,
## It breaks the connection between tensor and numPy array, then the change in that array doesn't affect the Tensor
array = array +1
array, tensor

(array([ 4.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [92]:
## Now the connection is lost so now we try to mpodify the array, It doesn't reflect the tensor
array[0] = 10
array, tensor

(array([10.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [93]:
## From tensor to numPy
numpy_tensor = ones_tensor.numpy()
numpy_tensor, ones_tensor.dtype ## numpy datatype changes to tensors default datatype

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32),
 torch.float32)

In [94]:
## Like in the case of numPy to Tensor, here,
## When modify the Tensor in place, the changes are reflected in the NumPy array, both the tensor and the array share the same memory.
ones_tensor[0,0] = 4
ones_tensor, numpy_tensor

(tensor([[4., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 array([[4., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [95]:
## When reassign the tensor to a new tensor,
## It breaks the connection between tensor and numPy array, then the change in that tensor doesn't affect the array
ones_tensor = ones_tensor + 1
ones_tensor, numpy_tensor

(tensor([[5., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 array([[4., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [96]:
## After the connection lost then if we try to mpodify the tensor, It doesn't reflect in array
ones_tensor[0,0] = 3
ones_tensor, numpy_tensor

(tensor([[3., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]),
 array([[4., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [98]:
## Reproducibility ==> Reduce the randomness in random
## Random_seed
random_tensor_1 = torch.rand(2,3)
random_tensor_2 = torch.rand(2,3)
print(random_tensor_1)
print(random_tensor_2)
print(random_tensor_1 == random_tensor_2)

tensor([[0.3325, 0.3530, 0.6534],
        [0.8080, 0.7704, 0.1904]])
tensor([[0.0192, 0.5834, 0.9673],
        [0.6667, 0.3559, 0.9011]])
tensor([[False, False, False],
        [False, False, False]])


In [101]:
## To set randomness in above case we use random_seed, random but reproducible tensor
### https://pytorch.org/docs/stable/generated/torch.manual_seed.html
### https://pytorch.org/docs/stable/notes/randomness.html
torch.manual_seed(0)
random_tensor_3 = torch.rand(2,3) ## manual_seed only works for a single block of code
torch.manual_seed(0) ## initialise every time if you need randomness
random_tensor_4 = torch.rand(2,3)
print(random_tensor_3)
print(random_tensor_4)
print(random_tensor_3 == random_tensor_4)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor([[True, True, True],
        [True, True, True]])


In [ ]:
## For more pytorch references ==>
### https://pytorch.org/tutorials/beginner/ptcheat.html